aws-iot-fleetwise-edge: disable service activation
ERROR: core-image-minimal-1.0-r0 do_rootfs: Postinstall scriptlets of ['aws-iot-fleetwise-edge'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

This is as there is no specific instance to activate. Thus deactivating.

(cherry picked from commit e72bc251df999239a31cde1cf9f45694967e8ef0)