aws-sdk-cpp: fix the ParseError
Add '###' to close the commented lines. Fixes the bitbake parsing
error caused by the trailing backslash:

ERROR: ParseError at meta-aws/recipes-sdk/aws-sdk-cpp/aws-sdk-cpp_1.11.291.bb:430:
Unparsed lines: ['# ec2;', '# s3-encryption;', '# identity-management;']
ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>