missing licence file path and checksum were added
To resolve following error,

ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: QA Issue: aws-greengrass-core-sdk-c: Recipe file fetches files and does not have license file information (LIC_FILES_CHKSUM) [license-checksum]
ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: aws-greengrass-core-sdk-c-git-r0 do_populate_lic: Function failed: populate_lic_qa_checksum
ERROR: Logfile of failure stored in: /home/sysadmin/git/QDN/workSpace/apq8009/apps_proc/build-qti-distro-fullstack-debug/tmp-glibc/work/armv7ahf-neon-oe-linux-gnueabi/aws-greengrass-core-sdk-c/git-r0/temp/log.do_populate_lic.19416
ERROR: Task (/home/sysadmin/git/QDN/workSpace/apq8009/apps_proc/poky/meta-aws/recipes-greengrass/greengrass-core-sdk/aws-greengrass-core-sdk-c_git.bb:do_populate_lic) failed with exit code '1'