recipes: don't use ${PN} in FILES
* this won't work for multilib where PN is e.g. "lib32-aws-c-common":
  ERROR: lib32-aws-c-common-0.8.3-r0 do_package: QA Issue: lib32-aws-c-common: Files/directories were installed but not shipped in any package:
    /usr/lib/libaws-c-common.so
    /usr/lib/libaws-c-common.so.1
    /usr/lib/libaws-c-common.so.1.0.0
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  lib32-aws-c-common: 3 installed and not shipped files. [installed-vs-shipped]

* drop all FILES* variables as the default values from bitbake.conf work
  better leave only:
  FILES:${PN}-dev += "${libdir}/*/cmake"
  as by default bitbake packages only ${libdir}/cmake in PN-dev, not in
  subdirectories

* verified with buildhistory (no change in FILELIST)

Signed-off-by: Martin Jansa <martin2.jansa@lgepartner.com>