aws-iot-device-sdk-python-v2.inc: fix BRANCH name and use fixed SRCREV
* master branch was renamed to main and even just parsing
  this recipe fails with:
    bb.data_smart.ExpansionError: Failure expanding variable SRCPV,
    expression was ${@bb.fetch2.get_srcrev(d)} which triggered
    exception FetchError: Fetcher failure: Unable to resolve
    'master' in upstream git repository in git ls-remote output
    for github.com/aws/aws-iot-device-sdk-python-v2.git
  because of AUTOREV use instead of fixed SRCREV

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>